import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import MyNavBar from "../components/mynavbar/MyNavBar";
import Footer from "../components/footer/Footer";
import waterDrop from '../resources/images/water_drop.png';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Auto 95 Clean</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <MyNavBar activepath={'/'} />
        <Image
            src={waterDrop}
            alt={'water-drop'}
            style={{width: '100%', height: "auto"}}
            className={'d-none d-md-block hide-image-transition'}
        />
        <div>
            <p>fefezfze</p>
            <p>fefezfze</p>
            <p>fefezfze</p>
            <p>fefezfze</p>
            <p>fefezfze</p>
            <p>fefezfze</p>
            <p>fefezfze</p>
            <p>fefezfze</p>
            <p>fefezfze</p>
            <p>fefezfze</p>
            <p>fefezfze</p>
            <p>fefezfze</p>
            <p>fefezfze</p>
            <p>fefezfze</p>
            <p>fefezfze</p>
            <p>fefezfze</p>
            <p>fefezfze</p>
            <p>fefezfze</p>
            <p>fefezfze</p>

        </div>
        <Footer />
    </>
  )
}
